name: PR
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node/issues/67#issuecomment-833764503
      - name: Prepare .npmrc
        run: envsubst < .npmrc.ci > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: corepack enable
      - run: pnpm install
      - run: pnpm m run build
