name: Release
on:
  push:
    branches:
      - master
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # https://github.com/actions/setup-node/issues/67#issuecomment-833764503
      - name: Prepare .npmrc
        run: envsubst < .npmrc.ci > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: corepack enable
      - run: pnpm install
      - uses: changesets/action@v1
        with:
          publish: pnpm release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
